export enum AdjustmentType {
  CONTRACTUAL = 'CONTRACTUAL',
  WRITE_OFF = 'WRITE_OFF',
  PATIENT_RESPONSIBILITY = 'PATIENT_RESPONSIBILITY',
  PAYER_REDUCTION = 'PAYER_REDUCTION',
  OTHER = 'OTHER',
}
