export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DOCS_REQUESTED = 'DOCS_REQUESTED',
  DOCS_RECEIVED = 'DOCS_RECEIVED',
  APPROVED = 'APPROVED',
  PROVISIONING = 'PROVISIONING',
  ONBOARDING = 'ONBOARDING',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
}
