export enum AssistanceLevel {
  INDEPENDENT = 'INDEPENDENT',
  SUPERVISED = 'SUPERVISED',
  VERBAL_PROMPT = 'VERBAL_PROMPT',
  PHYSICAL_ASSIST = 'PHYSICAL_ASSIST',
  FULL_ASSIST = 'FULL_ASSIST',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}
