export enum NotificationType {
  AUTH_THRESHOLD = 'AUTH_THRESHOLD',
  CLAIM_STATUS = 'CLAIM_STATUS',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  SHIFT_UPDATE = 'SHIFT_UPDATE',
  ONBOARDING_STATUS = 'ONBOARDING_STATUS',
  BREAK_GLASS = 'BREAK_GLASS',
  EVV_ALERT = 'EVV_ALERT',
  SYSTEM = 'SYSTEM',
}
