export enum PlatformRole {
  PLATFORM_OWNER = 'PLATFORM_OWNER',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  ONBOARDING_SPECIALIST = 'ONBOARDING_SPECIALIST',
  SUPPORT_ENGINEER = 'SUPPORT_ENGINEER',
  BILLING_OPERATOR = 'BILLING_OPERATOR',
  COMPLIANCE_AUDITOR = 'COMPLIANCE_AUDITOR',
}

export enum AgencyRole {
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  DSP = 'DSP',
  CLINICIAN = 'CLINICIAN',
  BILLING_SPECIALIST = 'BILLING_SPECIALIST',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  GUARDIAN = 'GUARDIAN',
}

export type UserRole = PlatformRole | AgencyRole;
